begin;

create table if not exists public.security_audit_events (
  id bigint generated by default as identity primary key,
  level text not null check (level in ('error')),
  event text not null check (event ~ '^[A-Za-z0-9_.:-]{1,80}$'),
  request_id text not null check (request_id ~ '^[A-Za-z0-9_-]{8,64}$'),
  route text not null check (route ~ '^[A-Za-z0-9_.:-]{1,80}$'),
  error_name text check (
    error_name is null or error_name ~ '^[A-Za-z0-9_.:-]{1,80}$'
  ),
  provider_status smallint check (
    provider_status is null or provider_status between 100 and 599
  ),
  outcome text check (
    outcome is null or outcome ~ '^[A-Za-z0-9_.:-]{1,80}$'
  ),
  created_at timestamptz not null default now()
);

create index if not exists security_audit_events_created_at_idx
  on public.security_audit_events (created_at desc);

create index if not exists security_audit_events_event_created_at_idx
  on public.security_audit_events (event, created_at desc);

alter table public.security_audit_events enable row level security;

revoke all on table public.security_audit_events from public, anon, authenticated;
grant insert, select, delete on table public.security_audit_events to service_role;
revoke all on sequence public.security_audit_events_id_seq from public, anon, authenticated;
grant usage, select on sequence public.security_audit_events_id_seq to service_role;

commit;
